// Generated by https://quicktype.io

export interface Product {
    id:          number;
    title:       string;
    price:       number;
    description: string;
    images:      string[];
    creationAt:  string;
    updatedAt:   string;
    category:    string;
}


